# Scheduler settings
queue: normal
ncpus: 1
walltime: 10:00
jobname: bowl1

# Model settings
model: mom
shortpath: /scratch/v45
exe: fms_MOM_solo.x
input: bowl1

# Postprocessing
collate:
  walltime: 10:00
  mem: 1GB
