format: yamanifest
version: 1.0
---
work/INPUT/gotmturb.inp:
  fullpath: /scratch/v45/aph502/mom/input/bowl1/gotmturb.inp
  hashes:
    binhash: 1730d092cdc5d86e234d3749857ed318
    md5: 3016ea3bccf1acd2c18eefdd6dbf02e9
work/INPUT/grid_spec.nc:
  fullpath: /scratch/v45/aph502/mom/input/bowl1/grid_spec.nc
  hashes:
    binhash: b79c406507e2b96725a08237e2165314
    md5: f571a0106c4a2eba38e3c407335e8cca
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/v45/aph502/mom/input/bowl1/ocean_temp_salt.res.nc
  hashes:
    binhash: d70322dece2f10aaacf751254a2acee7
    md5: f506e15417ed813fde3516a262ff35e5
